<?php

namespace Database\Seeders;

use App\Models\Product;
use Database\Seeders\Support\ProductArt;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        File::ensureDirectoryExists(public_path('images/products'));

        foreach ($this->catalog() as $item) {
            $slug = Str::slug($item['name']);
            $imagePath = "/images/products/{$slug}.svg";

            File::put(
                public_path($imagePath),
                ProductArt::generate($item['category'], $slug, $item['name'], $item['creator'])
            );

            Product::updateOrCreate(['slug' => $slug], [
                'name' => $item['name'],
                'category' => $item['category'],
                'creator' => $item['creator'],
                'tagline' => $item['tagline'],
                'description' => $item['description'],
                'details' => $item['details'],
                'price' => $item['price'],
                'compare_at_price' => $item['compare_at_price'] ?? null,
                'image' => $imagePath,
                'accent' => ProductArt::accent($slug),
                'stock' => $item['stock'],
                'featured' => $item['featured'] ?? false,
                'released_at' => now()->subDays($item['released_days_ago']),
            ]);
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function catalog(): array
    {
        return [
            // ----------------------------------------------------------
            // Books
            // ----------------------------------------------------------
            [
                'name' => 'The Lighthouse Variations',
                'category' => 'books',
                'creator' => 'Marguerite Olsen',
                'tagline' => 'A novel about the keepers of a light that refuses to go out.',
                'description' => "Three generations of keepers tend the same failing lighthouse on a Norwegian island, each convinced they'll be the last. Olsen writes weather the way other novelists write dialogue — it argues, it apologizes, it lies. The kind of book you finish at 2am and immediately hand to someone you love.",
                'details' => [
                    ['label' => 'Format', 'value' => 'Hardcover'],
                    ['label' => 'Pages', 'value' => '342'],
                    ['label' => 'Publisher', 'value' => 'Catalog Press'],
                    ['label' => 'Year', 'value' => '2025'],
                ],
                'price' => 2800,
                'stock' => 18,
                'featured' => true,
                'released_days_ago' => 12,
            ],
            [
                'name' => 'Salt & Cedar',
                'category' => 'books',
                'creator' => 'Theo Brandt',
                'tagline' => 'Essays on making things slowly in a world that won\'t wait.',
                'description' => 'Brandt spent a decade apprenticing with boatbuilders, bakers, and bladesmiths, and came back with one conviction: the slow way is usually the honest way. Fourteen essays on craft, patience, and the dignity of doing one thing well. Underline-everything writing.',
                'details' => [
                    ['label' => 'Format', 'value' => 'Paperback'],
                    ['label' => 'Pages', 'value' => '218'],
                    ['label' => 'Publisher', 'value' => 'Driftwood Editions'],
                    ['label' => 'Year', 'value' => '2024'],
                ],
                'price' => 1800,
                'stock' => 32,
                'released_days_ago' => 160,
            ],
            [
                'name' => 'Notes on Wandering',
                'category' => 'books',
                'creator' => 'Iris Delaunay',
                'tagline' => 'A pocket philosophy of getting productively lost.',
                'description' => 'Part walking memoir, part argument against the optimized life. Delaunay traces aimless routes through six cities and finds that the best ideas arrive uninvited, somewhere between the second wrong turn and the third café. Small enough for a coat pocket, which is exactly where it belongs.',
                'details' => [
                    ['label' => 'Format', 'value' => 'Paperback'],
                    ['label' => 'Pages', 'value' => '164'],
                    ['label' => 'Publisher', 'value' => 'Field Notes Library'],
                    ['label' => 'Year', 'value' => '2023'],
                ],
                'price' => 1600,
                'compare_at_price' => 2200,
                'stock' => 24,
                'released_days_ago' => 420,
            ],
            [
                'name' => "The Cartographer's Daughter",
                'category' => 'books',
                'creator' => 'Elena Maren',
                'tagline' => 'She inherited his maps. The blank spaces were a message.',
                'description' => "When mapmaker Aurelio Voss dies, his daughter discovers his life's work is riddled with deliberate errors — islands that don't exist, rivers that run backwards. Following the mistakes leads her across three continents and into the family history he spent forty years redrawing. A literary adventure with real teeth.",
                'details' => [
                    ['label' => 'Format', 'value' => 'Hardcover'],
                    ['label' => 'Pages', 'value' => '406'],
                    ['label' => 'Publisher', 'value' => 'Catalog Press'],
                    ['label' => 'Year', 'value' => '2025'],
                ],
                'price' => 3200,
                'stock' => 14,
                'released_days_ago' => 45,
            ],
            [
                'name' => 'Slow Bread',
                'category' => 'books',
                'creator' => 'Marta Olivetti',
                'tagline' => 'Forty loaves, four ingredients, zero shortcuts.',
                'description' => 'Olivetti ran a two-table bakery in Turin for thirty years and never once wrote down a recipe — until now. Forty formulas built on flour, water, salt, and time, photographed in the flat morning light of her actual kitchen. The sourdough chapter alone is worth the price.',
                'details' => [
                    ['label' => 'Format', 'value' => 'Hardcover'],
                    ['label' => 'Pages', 'value' => '288'],
                    ['label' => 'Publisher', 'value' => 'Hearth & Stone'],
                    ['label' => 'Year', 'value' => '2024'],
                ],
                'price' => 3400,
                'stock' => 21,
                'featured' => true,
                'released_days_ago' => 200,
            ],
            [
                'name' => 'Midnight at the Archive',
                'category' => 'books',
                'creator' => 'J. P. Castellan',
                'tagline' => 'A locked-room mystery where the room is a national library.',
                'description' => 'A rare manuscript vanishes from a sealed vault between the 2am and 3am security rounds. The only suspects: five archivists, each with a reason to want it gone, none with a way to get in. Castellan plays scrupulously fair with the clues — you will still get it wrong.',
                'details' => [
                    ['label' => 'Format', 'value' => 'Paperback'],
                    ['label' => 'Pages', 'value' => '356'],
                    ['label' => 'Publisher', 'value' => 'Nightjar Books'],
                    ['label' => 'Year', 'value' => '2023'],
                ],
                'price' => 1700,
                'stock' => 40,
                'released_days_ago' => 510,
            ],
            [
                'name' => 'The Quiet Machines',
                'category' => 'books',
                'creator' => 'Ada Lindqvist',
                'tagline' => 'Essays on technology that knows when to leave you alone.',
                'description' => 'Lindqvist spent fifteen years designing software and five more regretting most of it. These twelve essays sketch a different future: tools that respect attention, interfaces that end, machines content to be quiet. Required reading for anyone who builds things people are forced to use.',
                'details' => [
                    ['label' => 'Format', 'value' => 'Hardcover'],
                    ['label' => 'Pages', 'value' => '244'],
                    ['label' => 'Publisher', 'value' => 'Catalog Press'],
                    ['label' => 'Year', 'value' => '2025'],
                ],
                'price' => 2600,
                'stock' => 16,
                'released_days_ago' => 28,
            ],
            [
                'name' => 'Orchard',
                'category' => 'books',
                'creator' => 'Sam Whitford',
                'tagline' => 'Poems about inheritance, pruning, and what grows back.',
                'description' => "Whitford's third collection works a single hillside orchard through four seasons and three generations. Plain-spoken, precise, and quietly devastating — the title poem has been read at more weddings and funerals than its author can keep track of.",
                'details' => [
                    ['label' => 'Format', 'value' => 'Paperback'],
                    ['label' => 'Pages', 'value' => '96'],
                    ['label' => 'Publisher', 'value' => 'Loam Poetry'],
                    ['label' => 'Year', 'value' => '2022'],
                ],
                'price' => 1600,
                'stock' => 27,
                'released_days_ago' => 730,
            ],
            [
                'name' => 'How Buildings Remember',
                'category' => 'books',
                'creator' => 'Frida Engel',
                'tagline' => 'An architectural history of repair, told through nine buildings.',
                'description' => "A Lisbon tile facade patched for two centuries. A Kyoto temple rebuilt every generation, identically. A Chicago warehouse that refuses to become condos. Engel argues that maintenance — not construction — is architecture's highest art form, and makes the case beautifully.",
                'details' => [
                    ['label' => 'Format', 'value' => 'Hardcover'],
                    ['label' => 'Pages', 'value' => '312'],
                    ['label' => 'Publisher', 'value' => 'Meridian Arts'],
                    ['label' => 'Year', 'value' => '2024'],
                ],
                'price' => 3000,
                'compare_at_price' => 3800,
                'stock' => 9,
                'released_days_ago' => 280,
            ],
            [
                'name' => 'The Long Way Round',
                'category' => 'books',
                'creator' => 'Caleb Munro',
                'tagline' => 'Eleven months, four continents, one deliberately missed flight.',
                'description' => 'Munro was supposed to fly home from Lisbon on a Tuesday. Instead he started walking east. What follows is the rare travel memoir more interested in other people than in its author — generous, funny, and entirely free of life lessons, which is its own kind of wisdom.',
                'details' => [
                    ['label' => 'Format', 'value' => 'Paperback'],
                    ['label' => 'Pages', 'value' => '378'],
                    ['label' => 'Publisher', 'value' => 'Driftwood Editions'],
                    ['label' => 'Year', 'value' => '2023'],
                ],
                'price' => 1900,
                'stock' => 22,
                'released_days_ago' => 600,
            ],
            [
                'name' => 'Letters to a Young Cook',
                'category' => 'books',
                'creator' => 'Henri Bisset',
                'tagline' => 'Forty years of kitchen wisdom in twenty-six letters.',
                'description' => "Bisset ran the same twelve-seat bistro for four decades and turned down every expansion offer with the same sentence: 'The pan is already the right size.' His letters to an unnamed apprentice cover knife work, grief, salt, and ambition — roughly in that order. A kitchen classic in the making.",
                'details' => [
                    ['label' => 'Format', 'value' => 'Hardcover'],
                    ['label' => 'Pages', 'value' => '202'],
                    ['label' => 'Publisher', 'value' => 'Hearth & Stone'],
                    ['label' => 'Year', 'value' => '2025'],
                ],
                'price' => 2400,
                'stock' => 3,
                'released_days_ago' => 90,
            ],
            [
                'name' => 'Glass Houses',
                'category' => 'books',
                'creator' => 'Vivian Cho',
                'tagline' => 'Nine stories about the things neighbors pretend not to see.',
                'description' => "Cho sets every story on the same suburban cul-de-sac across forty years, and the result reads like a novel that's been shattered and beautifully reassembled. Sharp, humane, and frequently very funny about the small hypocrisies that hold communities together.",
                'details' => [
                    ['label' => 'Format', 'value' => 'Paperback'],
                    ['label' => 'Pages', 'value' => '232'],
                    ['label' => 'Publisher', 'value' => 'Nightjar Books'],
                    ['label' => 'Year', 'value' => '2024'],
                ],
                'price' => 1700,
                'stock' => 35,
                'released_days_ago' => 320,
            ],
            [
                'name' => 'The Weekend Naturalist',
                'category' => 'books',
                'creator' => 'Rosa Alvarez',
                'tagline' => 'A field guide for people who only have Saturdays.',
                'description' => "You don't need a sabbatical to notice things. Alvarez's guide covers fifty common species — birds, trees, mushrooms, clouds — with the explicit promise that all of them can be found within a mile of wherever you live. Illustrated by the author. Genuinely changes how you walk to the store.",
                'details' => [
                    ['label' => 'Format', 'value' => 'Flexibound'],
                    ['label' => 'Pages', 'value' => '256'],
                    ['label' => 'Publisher', 'value' => 'Field Notes Library'],
                    ['label' => 'Year', 'value' => '2024'],
                ],
                'price' => 2200,
                'stock' => 19,
                'released_days_ago' => 240,
            ],
            [
                'name' => 'Margins',
                'category' => 'books',
                'creator' => 'Iris Delaunay',
                'tagline' => 'A memoir told entirely through notes left in secondhand books.',
                'description' => "For twenty years Delaunay bought used books specifically for the marginalia, building an accidental archive of strangers' thoughts. Margins reconstructs five of those readers from their pencil marks alone. An astonishing formal experiment that somehow lands as deeply human.",
                'details' => [
                    ['label' => 'Format', 'value' => 'Hardcover'],
                    ['label' => 'Pages', 'value' => '268'],
                    ['label' => 'Publisher', 'value' => 'Catalog Press'],
                    ['label' => 'Year', 'value' => '2025'],
                ],
                'price' => 2700,
                'stock' => 0,
                'released_days_ago' => 75,
            ],

            // ----------------------------------------------------------
            // Vinyl
            // ----------------------------------------------------------
            [
                'name' => 'Golden Hour Static',
                'category' => 'vinyl',
                'creator' => 'Mirror Lakes',
                'tagline' => 'Warm analog synths for the last hour of daylight.',
                'description' => 'Recorded entirely to tape in a converted barn studio, Golden Hour Static sounds like the end of a long good day. Nine instrumental tracks that drift between ambient and slowcore without ever settling. Pressed on 180g vinyl with a gatefold sleeve worth framing.',
                'details' => [
                    ['label' => 'Format', 'value' => '180g LP, Gatefold'],
                    ['label' => 'Tracks', 'value' => '9'],
                    ['label' => 'Runtime', 'value' => '42 min'],
                    ['label' => 'Label', 'value' => 'Driftless Records'],
                ],
                'price' => 3200,
                'stock' => 15,
                'featured' => true,
                'released_days_ago' => 18,
            ],
            [
                'name' => 'Apartment Songs',
                'category' => 'vinyl',
                'creator' => 'Lena Marrow',
                'tagline' => 'Bedroom folk recorded in an actual bedroom.',
                'description' => "Marrow wrote these eleven songs over a single winter in a fourth-floor walkup, and you can hear the radiator in two of them — left in on purpose. Intimate without being precious, sad without being heavy. The closer, 'Fire Escape', has quietly become a standard.",
                'details' => [
                    ['label' => 'Format', 'value' => '140g LP'],
                    ['label' => 'Tracks', 'value' => '11'],
                    ['label' => 'Runtime', 'value' => '38 min'],
                    ['label' => 'Label', 'value' => 'Small Hours'],
                ],
                'price' => 2600,
                'stock' => 23,
                'released_days_ago' => 130,
            ],
            [
                'name' => 'Driftwood',
                'category' => 'vinyl',
                'creator' => 'The Cardinal South',
                'tagline' => 'Harmony-rich Americana from three siblings and one microphone.',
                'description' => "The Cardinal South cut Driftwood live around a single ribbon mic, the way their grandfather's band did in 1962. Twelve songs of porch-light Americana with the kind of blood-harmony you can't rehearse your way into. Includes a download code and a hand-numbered insert.",
                'details' => [
                    ['label' => 'Format', 'value' => '180g LP'],
                    ['label' => 'Tracks', 'value' => '12'],
                    ['label' => 'Runtime', 'value' => '44 min'],
                    ['label' => 'Label', 'value' => 'Driftless Records'],
                ],
                'price' => 2900,
                'stock' => 18,
                'released_days_ago' => 365,
            ],
            [
                'name' => 'Night Swimming Vol. II',
                'category' => 'vinyl',
                'creator' => 'Okudah',
                'tagline' => 'Deep, patient house music for after the party thins out.',
                'description' => "The second volume in Okudah's Night Swimming series goes deeper and slower — six extended cuts built for the hour when the dance floor belongs to the people who actually came to dance. Mastered loud, cut at 45rpm across two discs. A DJ-bag essential.",
                'details' => [
                    ['label' => 'Format', 'value' => '2xLP, 45rpm'],
                    ['label' => 'Tracks', 'value' => '6'],
                    ['label' => 'Runtime', 'value' => '51 min'],
                    ['label' => 'Label', 'value' => 'Submerge'],
                ],
                'price' => 3800,
                'stock' => 11,
                'released_days_ago' => 60,
            ],
            [
                'name' => 'Tape Hiss & Honey',
                'category' => 'vinyl',
                'creator' => 'Bedroom Archives',
                'tagline' => 'Lo-fi soul rescued from a box of forgotten cassettes.',
                'description' => 'In 2019 a producer bought a shoebox of unlabeled cassettes at an estate sale. Inside: a complete, unreleased soul record from 1974. Lovingly restored, lightly dusted with its original tape hiss, and finally given the pressing it deserved fifty years late.',
                'details' => [
                    ['label' => 'Format', 'value' => '180g LP'],
                    ['label' => 'Tracks', 'value' => '10'],
                    ['label' => 'Runtime', 'value' => '36 min'],
                    ['label' => 'Label', 'value' => 'Attic Light'],
                ],
                'price' => 3400,
                'compare_at_price' => 4200,
                'stock' => 7,
                'released_days_ago' => 410,
            ],
            [
                'name' => 'Meridian',
                'category' => 'vinyl',
                'creator' => 'Saint Cloche',
                'tagline' => 'Orchestral electronica that earns the word cinematic.',
                'description' => 'Saint Cloche scored two films before making the record she actually wanted to hear. Meridian moves a 40-piece string section through modular synth weather systems — enormous, precise, and somehow never cold. Audiophile pressing on translucent vinyl.',
                'details' => [
                    ['label' => 'Format', 'value' => '180g LP, Translucent'],
                    ['label' => 'Tracks', 'value' => '8'],
                    ['label' => 'Runtime', 'value' => '47 min'],
                    ['label' => 'Label', 'value' => 'Meridian Arts'],
                ],
                'price' => 4500,
                'stock' => 9,
                'released_days_ago' => 95,
            ],
            [
                'name' => 'Low Tide Hymns',
                'category' => 'vinyl',
                'creator' => 'Harbor Lights Choir',
                'tagline' => 'Sea shanties slowed down until they become prayers.',
                'description' => 'A twelve-voice choir from a Nova Scotia fishing town takes the work songs their grandparents sang and stretches them into something closer to Arvo Pärt than the pub. Recorded in an empty church at low tide. Unreasonably beautiful.',
                'details' => [
                    ['label' => 'Format', 'value' => '140g LP'],
                    ['label' => 'Tracks', 'value' => '9'],
                    ['label' => 'Runtime', 'value' => '40 min'],
                    ['label' => 'Label', 'value' => 'Small Hours'],
                ],
                'price' => 2800,
                'stock' => 26,
                'released_days_ago' => 540,
            ],
            [
                'name' => 'Analog Heart',
                'category' => 'vinyl',
                'creator' => 'Vera & The Volts',
                'tagline' => 'Garage rock with a Motown engine under the hood.',
                'description' => "Three chords, tambourine, and a frontwoman who sounds like she's having the best night of her life on every track. Analog Heart was recorded in four days and sounds like it — in the best possible way. Turn it up; the neighbors will understand.",
                'details' => [
                    ['label' => 'Format', 'value' => '140g LP'],
                    ['label' => 'Tracks', 'value' => '12'],
                    ['label' => 'Runtime', 'value' => '34 min'],
                    ['label' => 'Label', 'value' => 'Volt Sound'],
                ],
                'price' => 2400,
                'stock' => 31,
                'released_days_ago' => 220,
            ],
            [
                'name' => 'Kyoto Rain',
                'category' => 'vinyl',
                'creator' => 'Floating Garden',
                'tagline' => 'Ambient jazz recorded during one week of October rain.',
                'description' => "Piano, upright bass, brushed drums, and the actual rain on the studio roof, mic'd and mixed as a fourth instrument. Floating Garden's quietest and best record. The Japanese first pressing sold out in a day; this is the faithful international edition.",
                'details' => [
                    ['label' => 'Format', 'value' => '180g LP, Obi Strip'],
                    ['label' => 'Tracks', 'value' => '7'],
                    ['label' => 'Runtime', 'value' => '45 min'],
                    ['label' => 'Label', 'value' => 'Garden Recordings'],
                ],
                'price' => 3600,
                'stock' => 13,
                'featured' => true,
                'released_days_ago' => 25,
            ],
            [
                'name' => 'Slow Dances',
                'category' => 'vinyl',
                'creator' => 'Jules Marais',
                'tagline' => 'Eight waltzes for people who claim they can\'t dance.',
                'description' => "Marais wrote one waltz a year for eight years, each for a different couple in his life — a wedding, an anniversary, a reconciliation. Accordion, nylon guitar, and a string trio, pressed warm and quiet. The liner notes tell each couple's story and will absolutely make you cry.",
                'details' => [
                    ['label' => 'Format', 'value' => '140g LP'],
                    ['label' => 'Tracks', 'value' => '8'],
                    ['label' => 'Runtime', 'value' => '33 min'],
                    ['label' => 'Label', 'value' => 'Small Hours'],
                ],
                'price' => 2700,
                'stock' => 17,
                'released_days_ago' => 300,
            ],
            [
                'name' => 'Static Bloom',
                'category' => 'vinyl',
                'creator' => 'Velvet Antenna',
                'tagline' => 'Shoegaze maximalism with a pop heart buried in the noise.',
                'description' => "Velvet Antenna stack forty guitar tracks per song and somehow leave room for melodies you'll hum for weeks. Static Bloom is their breakthrough — the rare wall-of-sound record where the wall has windows. Pressed on heavyweight vinyl to survive the bass.",
                'details' => [
                    ['label' => 'Format', 'value' => '180g LP'],
                    ['label' => 'Tracks', 'value' => '10'],
                    ['label' => 'Runtime', 'value' => '48 min'],
                    ['label' => 'Label', 'value' => 'Volt Sound'],
                ],
                'price' => 3000,
                'compare_at_price' => 3600,
                'stock' => 20,
                'released_days_ago' => 180,
            ],
            [
                'name' => 'Country of Clouds',
                'category' => 'vinyl',
                'creator' => "Whistler's Union",
                'tagline' => 'Folk songs collected above 3,000 meters.',
                'description' => "Whistler's Union spent two summers in mountain villages across three continents, learning songs that have never been recorded. Country of Clouds sets them gently — voice, fiddle, harmonium — with field recordings of wind, bells, and one very vocal goat. A quiet marvel.",
                'details' => [
                    ['label' => 'Format', 'value' => '140g LP'],
                    ['label' => 'Tracks', 'value' => '11'],
                    ['label' => 'Runtime', 'value' => '41 min'],
                    ['label' => 'Label', 'value' => 'Attic Light'],
                ],
                'price' => 2800,
                'stock' => 4,
                'released_days_ago' => 470,
            ],
            [
                'name' => 'Paper Planets',
                'category' => 'vinyl',
                'creator' => 'The Orrery',
                'tagline' => 'Chamber pop with an astronomer\'s sense of scale.',
                'description' => "Every song on Paper Planets is named for a moon, and every arrangement orbits accordingly — tight, elliptical, occasionally eclipsed by a twelve-person brass section. The Orrery's most ambitious record, and the rare concept album that works even if you ignore the concept.",
                'details' => [
                    ['label' => 'Format', 'value' => '2xLP, Gatefold'],
                    ['label' => 'Tracks', 'value' => '14'],
                    ['label' => 'Runtime', 'value' => '58 min'],
                    ['label' => 'Label', 'value' => 'Garden Recordings'],
                ],
                'price' => 4200,
                'stock' => 8,
                'released_days_ago' => 350,
            ],

            // ----------------------------------------------------------
            // Board games
            // ----------------------------------------------------------
            [
                'name' => 'Tidewater',
                'category' => 'board-games',
                'creator' => 'Elin Sørensen',
                'tagline' => 'Build the harbor. Read the tides. Trust no forecast.',
                'description' => 'Each round the tide chart shifts, flooding some docks and stranding others — and the player who reads the water best wins. Tidewater plays in under an hour, teaches in five minutes, and has enough depth to anchor a weekly game night for years. Our most-recommended game, full stop.',
                'details' => [
                    ['label' => 'Players', 'value' => '2–4'],
                    ['label' => 'Playtime', 'value' => '45–60 min'],
                    ['label' => 'Ages', 'value' => '10+'],
                    ['label' => 'Complexity', 'value' => 'Medium'],
                ],
                'price' => 5400,
                'stock' => 12,
                'featured' => true,
                'released_days_ago' => 21,
            ],
            [
                'name' => 'Atlas Unbound',
                'category' => 'board-games',
                'creator' => 'Marco Tinelli',
                'tagline' => 'A map-drawing game where every table invents a new world.',
                'description' => "Flip a card, draw the coastline, name the mountains — by the end of a game of Atlas Unbound your table has made a world map that has never existed before and will never exist again. Plays solo to six. The pencil-and-paper game that converts people who 'don't play games'.",
                'details' => [
                    ['label' => 'Players', 'value' => '1–6'],
                    ['label' => 'Playtime', 'value' => '30–45 min'],
                    ['label' => 'Ages', 'value' => '8+'],
                    ['label' => 'Complexity', 'value' => 'Light'],
                ],
                'price' => 3400,
                'stock' => 25,
                'released_days_ago' => 140,
            ],
            [
                'name' => 'Market Day',
                'category' => 'board-games',
                'creator' => 'Hana Voss',
                'tagline' => 'A bustling trade game the whole family argues about — happily.',
                'description' => 'Buy low at dawn, sell high by dusk, and watch the market turn on a single dice roll. Market Day is the rare family game with genuine table talk — alliances, haggling, dramatic betrayals over the price of saffron. Twenty minutes a round; nobody plays just one.',
                'details' => [
                    ['label' => 'Players', 'value' => '3–6'],
                    ['label' => 'Playtime', 'value' => '20–30 min'],
                    ['label' => 'Ages', 'value' => '8+'],
                    ['label' => 'Complexity', 'value' => 'Light'],
                ],
                'price' => 2900,
                'stock' => 30,
                'released_days_ago' => 380,
            ],
            [
                'name' => 'Quarry',
                'category' => 'board-games',
                'creator' => 'Anders Lindholm',
                'tagline' => 'An abstract duel of stone and patience. Chess energy, no homework.',
                'description' => "Two players, forty stone tiles, zero luck. Quarry's rules fit on a postcard, but the decision space opens like a canyon — every piece you take reshapes the board for both of you. Solid beechwood components that feel like they'll outlive the house. A modern abstract classic.",
                'details' => [
                    ['label' => 'Players', 'value' => '2'],
                    ['label' => 'Playtime', 'value' => '15–25 min'],
                    ['label' => 'Ages', 'value' => '8+'],
                    ['label' => 'Complexity', 'value' => 'Light'],
                ],
                'price' => 3800,
                'stock' => 16,
                'released_days_ago' => 260,
            ],
            [
                'name' => 'Signal & Fog',
                'category' => 'board-games',
                'creator' => 'Petra Nyland',
                'tagline' => 'A cooperative lighthouse game. The fog is winning.',
                'description' => 'Ships are coming in and the fog is thicker every round. Signal & Fog hands your table one shared problem — keep the light burning, the horns sounding, and the fleet alive — and lets you fail together gloriously. The two-player version is a perfect date night with stakes.',
                'details' => [
                    ['label' => 'Players', 'value' => '1–4 (co-op)'],
                    ['label' => 'Playtime', 'value' => '40–60 min'],
                    ['label' => 'Ages', 'value' => '12+'],
                    ['label' => 'Complexity', 'value' => 'Medium'],
                ],
                'price' => 4900,
                'compare_at_price' => 5900,
                'stock' => 10,
                'released_days_ago' => 190,
            ],
            [
                'name' => 'Grove',
                'category' => 'board-games',
                'creator' => 'Yuki Tanaka',
                'tagline' => 'Plant, graft, and grow the orchard of your engine-building dreams.',
                'description' => 'Grove starts with three saplings and ends with a humming ecosystem of grafts, pollinators, and harvest combos that cascade for full minutes. The engine-builder for people who find spreadsheets soothing — and the art, all woodblock prints, is frame-worthy.',
                'details' => [
                    ['label' => 'Players', 'value' => '1–4'],
                    ['label' => 'Playtime', 'value' => '60–90 min'],
                    ['label' => 'Ages', 'value' => '12+'],
                    ['label' => 'Complexity', 'value' => 'Heavy'],
                ],
                'price' => 6200,
                'stock' => 8,
                'released_days_ago' => 110,
            ],
            [
                'name' => 'Six Bridges',
                'category' => 'board-games',
                'creator' => 'Claude Berger',
                'tagline' => 'Route-building across a city that floods every third round.',
                'description' => "Connect the districts, collect the tolls, and pray the river behaves — it won't. Six Bridges takes the comfortable rhythm of a route-building game and adds just enough chaos to keep the engineers at your table honest. Plays brilliantly at every player count.",
                'details' => [
                    ['label' => 'Players', 'value' => '2–5'],
                    ['label' => 'Playtime', 'value' => '45–60 min'],
                    ['label' => 'Ages', 'value' => '10+'],
                    ['label' => 'Complexity', 'value' => 'Medium'],
                ],
                'price' => 4400,
                'stock' => 14,
                'released_days_ago' => 330,
            ],
            [
                'name' => 'Ember & Oak',
                'category' => 'board-games',
                'creator' => 'Sofia Reyes',
                'tagline' => 'A two-player dueling card game of fire and forest.',
                'description' => 'One of you plays the wildfire; the other plays the forest, regrowing as fast as it burns. Ember & Oak is asymmetric, fast, and genuinely tense — each side feels overpowered until you switch seats. Fifteen minutes a match, best of three, rematch demanded immediately.',
                'details' => [
                    ['label' => 'Players', 'value' => '2'],
                    ['label' => 'Playtime', 'value' => '15–20 min'],
                    ['label' => 'Ages', 'value' => '10+'],
                    ['label' => 'Complexity', 'value' => 'Light'],
                ],
                'price' => 2900,
                'stock' => 28,
                'released_days_ago' => 85,
            ],
            [
                'name' => "The Botanist's Gambit",
                'category' => 'board-games',
                'creator' => 'Ingrid Falk',
                'tagline' => 'Victorian plant-hunting, worker placement, and gentle sabotage.',
                'description' => "Race rival expeditions to catalog the rarest specimens of 1887 — by funding, by forgery, or by quietly misdirecting their porters. The Botanist's Gambit wraps a sharp worker-placement core in period botanical art so good the cards double as a deck of prints.",
                'details' => [
                    ['label' => 'Players', 'value' => '2–4'],
                    ['label' => 'Playtime', 'value' => '60–75 min'],
                    ['label' => 'Ages', 'value' => '12+'],
                    ['label' => 'Complexity', 'value' => 'Medium-Heavy'],
                ],
                'price' => 5800,
                'stock' => 11,
                'released_days_ago' => 230,
            ],
            [
                'name' => 'Parlor Birds',
                'category' => 'board-games',
                'creator' => 'Émile Fournier',
                'tagline' => 'A trick-taking game with songbirds, secrets, and one cuckoo.',
                'description' => "Classic trick-taking with one elegant twist: the cuckoo card swaps your hand with an opponent's the moment it's played. Parlor Birds is small enough for a coat pocket, deep enough for a tournament, and pretty enough that people keep stealing the box for shelf decor.",
                'details' => [
                    ['label' => 'Players', 'value' => '3–5'],
                    ['label' => 'Playtime', 'value' => '20–30 min'],
                    ['label' => 'Ages', 'value' => '8+'],
                    ['label' => 'Complexity', 'value' => 'Light'],
                ],
                'price' => 2200,
                'stock' => 36,
                'released_days_ago' => 50,
            ],
            [
                'name' => 'Northwind Saga',
                'category' => 'board-games',
                'creator' => 'Bjorn Eskildsen',
                'tagline' => 'A campaign adventure across twelve linked voyages.',
                'description' => 'Your longship, your crew, your saga — written one voyage at a time across a twelve-session campaign where the map, the crew, and the legend persist between games. Northwind Saga is the campaign game for groups who finish what they start. No two tables tell the same story.',
                'details' => [
                    ['label' => 'Players', 'value' => '1–4 (campaign)'],
                    ['label' => 'Playtime', 'value' => '90–120 min'],
                    ['label' => 'Ages', 'value' => '14+'],
                    ['label' => 'Complexity', 'value' => 'Heavy'],
                ],
                'price' => 7900,
                'stock' => 6,
                'released_days_ago' => 150,
            ],
            [
                'name' => 'Stacks',
                'category' => 'board-games',
                'creator' => 'Nora Quist',
                'tagline' => 'Tile-laying in a library where the books shelve themselves.',
                'description' => 'Build the stacks, shelve by color or subject, and earn the affection of an extremely judgmental cat token. Stacks is the cozy tile-layer that somehow ends every round with someone gasping at a 24-point combo. The game we hand to people who loved their first game night.',
                'details' => [
                    ['label' => 'Players', 'value' => '1–4'],
                    ['label' => 'Playtime', 'value' => '30–45 min'],
                    ['label' => 'Ages', 'value' => '8+'],
                    ['label' => 'Complexity', 'value' => 'Light'],
                ],
                'price' => 3600,
                'stock' => 22,
                'featured' => true,
                'released_days_ago' => 35,
            ],
        ];
    }
}
